from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
import secrets

from . import conf


def gen_secret_token() -> str:
    """Generate a cryptographically secure random hex token.

    Returns:
        A 64-character hexadecimal string (32 random bytes).
    """
    return secrets.token_hex(32)


class ECPNonce(models.Model):
    """One-time challenge nonce used during ECP authentication.

    A nonce is generated by the server, signed by the client, and consumed
    immediately after a successful authentication attempt.
    """

    value = models.CharField(max_length=64, default=gen_secret_token, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    used = models.BooleanField(default=False)

    def is_valid(self) -> bool:
        """Check whether this nonce can still be used for authentication.

        Returns:
            True if the nonce has not been used and has not exceeded the
            configured lifetime (``NONCE_LIFETIME`` Django setting).
        """
        nonce_age = timezone.now() - self.created_at
        return (not self.used) and (
            nonce_age.total_seconds() < conf.get_nonce_lifetime().total_seconds()
        )

    def consume(self) -> None:
        """Mark the nonce as used, preventing any future authentication with it."""
        self.used = True
        self.save()


class ECPCertificate(models.Model):
    """Public X.509 certificate associated with a Django user.

    Stores only the public certificate. The corresponding private key is
    never sent to or stored by the server.
    """

    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    certificate_pem = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
