# Generated by Django 6.0.3 on 2026-03-27 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecp_auth", "0002_alter_ecpcertificate_taxpayer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ecpcertificate",
            name="taxpayer_id",
        ),
    ]
