# Generated by Django 6.0.3 on 2026-03-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp_auth', '0003_remove_taxpayer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecpcertificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
